name: test workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
jobs:
    build:
        runs-on: halo
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: List directory
              run: ls -la

