name: test workflow
run-name: Run started by @${{github.actor }}
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
env:
    PIPE: cicd
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: List directory
              run: ls -la
            - name: Access context property
              run: 'echo "This is passed env PIPE: ${{ env.PIPE }}"'

