name: test workflow
run-name: Run started by @${{github.actor }}
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
env:
    PIPE: cicd
jobs:
    build:
        if: ${{ vars.EXEC_WF == 'true' }}
        runs-on: ubuntu-latest
        env:
            TOKEN: ${{ github.actor }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: List directory
              run: ls -la
            - name: Access context property
              run: 'echo "This is passed env PIPE: ${{ env.PIPE }}"'
            - name: Expand default env variables
              run: echo my repository $GITHUB_REPOSITORY
            - name: Expand configuration variables
              run: echo my file to check ${{ vars.FILE_TO_CHECK }}



